import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#deccff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "primary-fixed": "#e2dfff",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#444173",
        "on-secondary-container": "#514f81",
        "error-container": "#ffdad6",
        "primary-container": "#4a40e0",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary": "#5700bf",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#25005a",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#712ae1",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#181445",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "primary": "#301ec9",
        "on-primary-fixed": "#0f0069",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-tertiary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#e3dfff",
        "secondary-container": "#c7c3fe",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#eaddff",
        "outline": "#797586",
        "on-surface-variant": "#484554",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#c4c1fb",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-primary-container": "#d2d0ff",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#c3c0ff",
        "outline-variant": "#c9c4d7",
        "secondary": "#5b598c",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
